### ISSUE TITLE
Beef commands not working

### ISSUE THREAD

**Issue by Neymar8091** [beefproject/beef#1410]
Everytime I use beef it works besides the fact that commands dont work. I open the data on a command once it has been executed and nothing shows and nothing happens from my computer to the windows machine. Ive tried updating beef but that didnt work. Re-executing doesnt work either. What do I do?

**Comment by bcoles** [comment]
Ensure you're using the [latest version of BeEF](https://github.com/beefproject/beef/releases/tag/beef-0.4.7.0).


#### Environment

What version/revision of BeEF are you using?

On what version of Ruby?

On what browser?

On what operating system?


#### Configuration

Are you using a non-default configuration?

Have you enabled or disabled any BeEF extensions?


#### Summary

Please provide a summary of the issue.


#### Expected Behaviour

What was the expected result?


#### Actual Behaviour

What was the actual result?


#### Steps to Reproduce

Please provide steps to reproduce this issue.


#### Additional Information

Please provide any additional information which may be useful in resolving this issue, such as debugging output and relevant screen shots.

**Comment by Neymar8091** [comment]
beef:0.4.6.1
Ruby:2.3.3
Firefox
Linux
default configurations
enabled console shell extension
summary: I use beef and whenever I try to execute any command module (green,orange,white,red) it shows no data and it doesn't execute on the windows machine.
I expected the command to show some kind of data as shown here: https://goo.gl/images/JNRiay and I expected for the command to run through the machine.
The actual result was no data and the command, whatever it was, not running through the machine.
I do not have anymore info...

**Comment by bcoles** [comment]
@Neymar8091 ah there's your problem. The console extension is no longer supported. It breaks BeEF. Disable it and you should be fine.

**Comment by bcoles** [comment]
@Neymar8091 Also, BeEF version 0.4.6.1-alpha is over a year old. Try cloning from GitHub:

``` sh
git clone https://github.com/beefproject/beef
cd beef
bundle install
```

**Comment by Neymar8091** [comment]
Everytime i hook something it comes up with this:

2017-06-29 21:08:16 - NameError - uninitialized constant Rack::File::Iterator:
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:261:in `body'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1082:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1091:in `dispatch!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
	/var/lib/gems/2.3.0/gems/rack-2.0.3/lib/rack/null_logger.rb:9:in `call'
	/usr/lib/ruby/vendor_ruby/rack/head.rb:13:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:194:in `call'
	/var/lib/gems/2.3.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1955:in `call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:66:in `block in call'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `each'
	/usr/lib/ruby/vendor_ruby/rack/urlmap.rb:50:in `call'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:86:in `block in pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `catch'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:84:in `pre_process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:53:in `process'
	/usr/lib/ruby/vendor_ruby/thin/connection.rb:39:in `receive_data'
	/var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
	/var/lib/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	/usr/lib/ruby/vendor_ruby/thin/backends/base.rb:73:in `start'
	/usr/lib/ruby/vendor_ruby/thin/server.rb:162:in `start'
	/usr/share/beef/beef/core/main/server.rb:125:in `start'
	./beef:178:in `<main>'

**Comment by rxstranglove** [comment]
@Neymar8091 it looks like these this issue is a problem with sinatra 2.0.0. I was facing the same issue on Kali and resolved it by editing the sinatra/base.rb. I appended '::' to Rack::File:Iterator in the value.is_a?() equality. So line 261
`unless request.head? || value.is_a?(Rack::File::Iterator) || value.is_a?(Stream)`
Should be changed to:
`unless request.head? || value.is_a?(::Rack::File::Iterator) || value.is_a?(Stream)`

Note, once I did this I was facing an undefined method `extract_multipart' for Rack::Multipart:Module error which was resolved by modifying the rack's request.rb to require 'rack/multipart.rb'.

Let me know if that works out for you!

**Comment by bcoles** [comment]
Thanks @rxstranglove

I was literally just about to reply.

@Neymar8091 did disabling the console extension fix your issue?

Did you upgrade to the latest version of BeEF from Github?

I recently updated the dependencies. It's possible that there's an issue with the newer version of Rack.

See if this helps:

```sh
rm Gemfile.lock
bundle install
```

**Comment by bcoles** [comment]
@rxstranglove @Neymar8091 I've rolled back Rack to 1.6.x and tested successfully on Kali Rolling.

Please do `git checkout Gemfile.lock && git pull` and verify this works for you.

**Comment by Neymar8091** [comment]
All of the above from @bcoles and @rxstranglove worked but my commands still show no data and still don't run through the windows machine

**Comment by bcoles** [comment]
@Neymar8091 To clarify:

* You've done a `git pull` to update to the latest version of BeEF from GitHub, and `bundle install` to install the dependencies ?
* You've restarted BeEF and restarted whichever browser you were hooking ?
* You can send commands to a hooked browser running on Linux, and it works fine, but not on a hooked browser on Windows ?

Is the Windows host running anti-virus?

What browser are you hooking? What version of Windows?

What command module are you running?

Do you get any output in terminal or the browser web development console?

Try enabling `debug` in the beef `config.yaml` file and see if you get any additional output.

**Comment by bcoles** [comment]
Also, have you installed NodeJS?

**Comment by Neymar8091** [comment]
Updated and installed latest dependencies.
I've tried restarted beef and the hooked browser and computer.
I send a command to any computer on any operating system and it doesn't run through or show any data

**Comment by Neymar8091** [comment]
The windows isn't running an antivirus. 
I've hooked Microsoft edge.
Windows 10.
I'm running command redirect brower and nearly all the detect commands

**Comment by Neymar8091** [comment]
No output shown.
I will try enabling debug mode.
I don't know if I have NodeJS

**Comment by bcoles** [comment]
I don't have an Edge browser or Windows 10 system to test with.

I have no issues hooking browsers on multiple versions of Windows with multiple different browsers.

Can you hook other browsers? Do they execute commands?

**Comment by Neymar8091** [comment]
I can hook other browsers but the commands don't get executed on the browser

**Comment by bcoles** [comment]
I can't reproduce this issue.

There's not much else I can do to help without the console output and debugging info.

**Comment by rxstranglove** [comment]
@bcoles for completeness sake; reverting my changes, and pulling the latest worked for me. 
Thanks!

**Comment by bcoles** [comment]
Thanks @rxstranglove 

My bad I guess. I tested the updated dependencies on Kali 1.6 not Kali Rolling before pushing.

**Comment by bcoles** [comment]
@Neymar8091 any luck with this? Can you provide the console output with `debug: true` set in `config.yaml` ?

**Comment by bcoles** [comment]
Closing this issue. The `rack` dependency issue has been resolved.

If the problem persists, please open a new issue. Be sure to set `debug: true` set in `config.yaml` and provide the console output.

**Comment by Teiresias1** [comment]
Same issue here did you solved it ?

**Comment by bcoles** [comment]
> 
> 
> Same issue here did you solved it ?

This issue was solved 4 years ago.
