### ISSUE TITLE
some files not are installing

### ISSUE THREAD

**Issue by Xcalibur69** [beefproject/beef#2614]
1. Bundler::GemNotFound: Could not find unf-0.1.4.gem for installation
2. An error occurred while installing unf (0.1.4), and Bundler cannot continue.
3. An error occurred while installing xmlrpc (0.3.2), and Bundler cannot continue.
Please Help For Installing BeEF

**Comment by bcoles** [comment]
Try:

```
gem install xmlrpc
gem install unf
```

**Comment by tolstoy88** [comment]
An error occurred while installing domain_name (0.5.20190701), and
Bundler cannot continue.                                                       

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    http was resolved to 4.4.1, which depends on
      http-cookie was resolved to 1.0.5, which depends on
        domain_name

Someone could help me with this problem installing Beef

**Comment by bcoles** [comment]
```
gem install domain_name
```

**Comment by mateuseap** [comment]
That's what worked for me:

```
sudo gem install xmlrpc
sudo gem install unf
sudo gem install domain_name
sudo gem install http-cookie
```

After installing these gems the `sudo ./install` command worked properly, thanks @bcoles :)

**Comment by samvanooijen** [comment]
Hi all, it looks like the error as mentioned in the original post above is still happening. For instance, after following this guide (https://itsfoss.com/install-gedit-ubuntu/) for installing it on Ubuntu, `sudo ./install` fails to install `xmlrpc` and shows this error:

```text
Bundler::GemNotFound: Could not find xmlrpc-0.3.2.gem for installation
  /var/lib/gems/3.0.0/gems/bundler-2.4.12/lib/bundler/source/rubygems.rb:157:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.12/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.12/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.4.12/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.12/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.4.12/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.4.12/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.4.12/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.4.12/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.4.12/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing xmlrpc (0.3.2), and Bundler cannot continue.
```

**Comment by samvanooijen** [comment]
PS: forgot to say, installing `xmlrpc` by hand with `sudu gem install xmlrpc` works, and running `sudo ./install` afterwards runs fine.

(on Ubuntu, it won't install without `sudo`, but that's another issue)

**Comment by bcoles** [comment]
https://github.com/beefproject/beef/wiki/FAQ#bundle-install-doesnt-work
