### ISSUE TITLE
Beef-XSS project "Authentication form not seen in Kali Linux"

### ISSUE THREAD

**Issue by manopaul** [beefproject/beef#988]
Running Beef from the menu in Kali Linux after update and upgrade does not show the login form in http://<ip>:3000/ui/panel or http://<ip>:3000/ui/authentication 
Only the BeEF logo image (of the bull) is shown. 
Did bleeding-edge-repo pull as well as uninstalled and reinstalled beef-xss but the issue was not fixed. 
After researching and trying for hours, I came about a workaround ...
Finally from terminal, I ran 'ruby beef' command (prefix with ruby) instead of just './beef'in the beef-xss folder and then opened a browser and navigated to the http://<ip>:3000/ui/authentication and it worked. 
I wonder if it is a javacript bundling issue that generates the login form or a if has something to do with the ruby gems bundle (which were all checked but had no errors). 
Thank you for your support in advance. 
Mano 'dash4rk' Paul

**Comment by joseph-kovacs** [comment]
This is still a major issue with BeEF. I just rant multiple installations on Ubuntu 14.04 and ran into two issues. The first was no log in window available due to missing the following file: /ui/media/javascript-min/web_ui_auth.js

Messing with RVM (https://rvm.io/rvm/install) a bit I could finally get it to show up, but log into the panel using beef/beef and the following file is missing making the panel unusable: /ui/media/javascript-min/web_ui_all.js

Has there been any solution to either of these issues?

**Comment by joseph-kovacs** [comment]
Found a solution: 

rvm install 1.9.3-p484
rvm use 1.9.3 -- default
See: https://github.com/beefproject/beef/blob/master/INSTALL.txt

It looks like BeEF is VERY dependent on that RVM version at least for Ubuntu.

**Comment by offensive-security** [comment]
RVM is definitely not a recommend solution for Kali and beef. The issue for the bug described (https://bugs.kali.org/view.php?id=1130) was sue to insufficient permissions on the /usr/share/beef-xss/extensions/admin_ui/media/javascript-min/ directory, and has been fixed in subsequent releases of beef in Kali. Beef XSS works well in Kali-rolling now, by simply:

/etc/init.d/beef-xss start
and then browsing to : 
http://localhost:3000/ui/authentication

**Comment by ziflar** [comment]
yes the problem appears when ruby is updated to the 2.3.0 version
for the first installation of kali rolling, I proceeded as follows::
BEFORE DOING an apt-update,apt-upgrade,apt dist-upgrade.!!!!!!

                 echo " ruby hold" | dpkg --set-selections
                 echo " ruby2.2 hold" | dpkg --set-selections
                 echo " ruby2.2-dev:amd64 hold" | dpkg --set-selections
                 apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y

I just block the ruby updating and it works fine

**Comment by Kuhitacop** [comment]
I'm still having this issue in Parrot
Any ideas?
Thanks in advance!! <3

**Comment by wifiuk** [comment]
using kali 2018 latest versuion
even using the following comman
/etc/init.d/beef-xss start
i see no login page only the bull logo

**Comment by farsx** [comment]
@wifiuk 
I confirm the issue with latest kali-rolling.

@beefproject 
The problem seems to be the uglifier API that minify JS code:
https://github.com/beefproject/beef/blob/836c0c97e51a750d417704faa0fc86ad1753b67c/extensions/admin_ui/api/handler.rb#L22

It throws this error:
*API Fire Error: SyntaxError: Unexpected token } in {:owner=>BeEF::Extension::AdminUI::API::Handler, :id=>18}.mount_handler()*

As a quick-and-dirty workaround you can substitute the line:
 `minified = Uglifier.compile(evaluated)`
with:
 `minified = evaluated`

**Comment by krazyghostcrawler** [comment]
I have the same problem on Parrot Security GNU/Linux any help will be highly appreciated. Parrot Release 3.11 32-bit, Kernel Linux 4.14.0-parrot13-686-pae i686.

**Comment by bcoles** [comment]
@krazyghostcrawler this issue is closed. Please search the existing issues and if you don't find your answer then create a new issue.
